export const SIGN_UP = {
    REQUEST_ALL: 'REQUEST_ALL_USER_SIGN_UP',
    RESPONSE_ALL: 'RESPONSE_ALL_USER_SIGN_UP',
    REQUEST : 'REQUEST_SIGN_UP',
    ERROR: 'ERROR_SIGN_UP',
    SUCCESS: 'SUCCESS_SIGN_UP'
}